version: '3.9'

services:
  database:
    image: mysql:5.7
    container_name: database_otserv
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/data/mysql

volumes:
  mysqldata:
    driver: local
